CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text,
  display_name text NOT NULL,
  avatar_url text,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'disabled')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique
  ON users (lower(email))
  WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS workspaces (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'archived', 'deleted')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS workspaces_created_by_user_id_idx
  ON workspaces (created_by_user_id);

CREATE TABLE IF NOT EXISTS workspace_members (
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member'
    CHECK (role IN ('owner', 'admin', 'member')),
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'invited', 'disabled')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  joined_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, user_id)
);

CREATE INDEX IF NOT EXISTS workspace_members_user_id_idx
  ON workspace_members (user_id);

CREATE TABLE IF NOT EXISTS conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  created_by_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  title text NOT NULL DEFAULT '新的对话',
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'archived', 'deleted')),
  mode text NOT NULL DEFAULT 'chat',
  default_model text,
  last_message_id uuid,
  last_message_at timestamptz,
  message_count integer NOT NULL DEFAULT 0 CHECK (message_count >= 0),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS conversations_workspace_status_idx
  ON conversations (workspace_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS conversations_created_by_user_id_idx
  ON conversations (created_by_user_id);

CREATE TABLE IF NOT EXISTS conversation_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role text NOT NULL
    CHECK (role IN ('user', 'assistant', 'system', 'tool')),
  kind text NOT NULL DEFAULT 'message'
    CHECK (
      kind IN (
        'message',
        'reasoning',
        'tool_call',
        'tool_result',
        'workflow_status'
      )
    ),
  sender_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
  parent_message_id uuid REFERENCES conversation_messages(id) ON DELETE SET NULL,
  sequence_no bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  content text NOT NULL DEFAULT '',
  content_format text NOT NULL DEFAULT 'markdown'
    CHECK (content_format IN ('text', 'markdown', 'json')),
  status text NOT NULL DEFAULT 'completed'
    CHECK (status IN ('queued', 'streaming', 'completed', 'failed', 'cancelled')),
  request_id text,
  workflow_run_id uuid,
  agent_run_id uuid,
  tool_call_id text,
  tool_name text,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS conversation_messages_conversation_sequence_idx
  ON conversation_messages (conversation_id, sequence_no);

CREATE INDEX IF NOT EXISTS conversation_messages_sender_user_id_idx
  ON conversation_messages (sender_user_id);

CREATE INDEX IF NOT EXISTS conversation_messages_request_id_idx
  ON conversation_messages (request_id)
  WHERE request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS conversation_messages_workflow_run_id_idx
  ON conversation_messages (workflow_run_id)
  WHERE workflow_run_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS conversation_messages_agent_run_id_idx
  ON conversation_messages (agent_run_id)
  WHERE agent_run_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS conversation_messages_tool_call_id_idx
  ON conversation_messages (tool_call_id)
  WHERE tool_call_id IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'conversations_last_message_id_fkey'
  ) THEN
    ALTER TABLE conversations
      ADD CONSTRAINT conversations_last_message_id_fkey
      FOREIGN KEY (last_message_id)
      REFERENCES conversation_messages(id)
      ON DELETE SET NULL;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS workspaces_set_updated_at ON workspaces;
CREATE TRIGGER workspaces_set_updated_at
BEFORE UPDATE ON workspaces
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS workspace_members_set_updated_at ON workspace_members;
CREATE TRIGGER workspace_members_set_updated_at
BEFORE UPDATE ON workspace_members
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS conversations_set_updated_at ON conversations;
CREATE TRIGGER conversations_set_updated_at
BEFORE UPDATE ON conversations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS conversation_messages_set_updated_at ON conversation_messages;
CREATE TRIGGER conversation_messages_set_updated_at
BEFORE UPDATE ON conversation_messages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
